version: '3.4'
services:
  mysql:
    restart: always
    # image: mysql
    build:
      dockerfile: Dockerfile
      context: ./database/mysql/
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db

  api_server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/api/
    container_name: api_server
    ports:
      - "80:80"