version: '3.4'
services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
  api_server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/
    container_name: api_server
    environment:
      DB_PASSWORD: "root"
      DB_USER: "postgres"
      POSTGRES_DB: "test_db"
      DB_PORT: "5432"
      DB_HOST: "10.61.21.144"
    ports:
      - "80:80"