  version: '3.4'
  services:
    mysql:
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./database/mysql
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "abcdabcd"
