from config.db import Base
from sqlalchemy import Column, Integer, String, SMALLINT, Float, Enum, Date


class EngineInspectionData(Base):
    __tablename__ = "engine_inspection"
    appointmentId = Column(String(255), primary_key=True, index=True)
    inspectionDate = Column(Date)
    inspectionStartTime = Column(String(255))
    year = Column(SMALLINT)
    month = Column(SMALLINT)
    engineTransmission_battery_value = Column(String(255))
    engineTransmission_battery_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_battery_cc_value_1 = Column(String(255), nullable=True)
    engineTransmission_battery_cc_value_2 = Column(String(255), nullable=True)
    engineTransmission_battery_cc_value_3 = Column(String(255), nullable=True)
    engineTransmission_battery_cc_value_4 = Column(String(255), nullable=True)
    engineTransmission_engineoilLevelDipstick_value = Column(String(255))
    engineTransmission_engineOilLevelDipstick_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_engineOil = Column(String(255))
    engineTransmission_engineOil_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_1 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_2 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_3 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_4 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_5 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_6 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_7 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_8 = Column(String(255), nullable=True)
    engineTransmission_engineOil_cc_value_9 = Column(String(255), nullable=True)
    engineTransmission_engine_value = Column(String(255))
    engineTransmission_engine_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_1 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_2 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_3 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_4 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_5 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_6 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_7 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_8 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_9 = Column(String(255), nullable=True)
    engineTransmission_engine_cc_value_10 = Column(String(255), nullable=True)
    engineTransmission_coolant_value = Column(String(255))
    engineTransmission_coolant_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_coolant_cc_value_1 = Column(String(255), nullable=True)
    engineTransmission_coolant_cc_value_2 = Column(String(255), nullable=True)
    engineTransmission_coolant_cc_value_3 = Column(String(255), nullable=True)
    engineTransmission_engineMounting_value = Column(String(255))
    engineTransmission_engineMounting_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_engineSound_value = Column(String(255))
    engineTransmission_engineSound_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_engineSound_cc_value_1 = Column(String(255), nullable=True)
    engineTransmission_engineSound_cc_value_2 = Column(String(255), nullable=True)
    engineTransmission_engineSound_cc_value_3 = Column(String(255), nullable=True)
    engineTransmission_engineSound_cc_value_4 = Column(String(255), nullable=True)
    engineTransmission_engineSound_cc_value_5 = Column(String(255), nullable=True)
    engineTransmission_exhaustSmoke_value = Column(String(255))
    engineTransmission_exhaustSmoke_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_engineBlowByBackCompression_value = Column(String(255))
    engineTransmission_engineBlowByBackCompression_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_clutch_value = Column(String(255))
    engineTransmission_clutch_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_clutch_cc_value_1 = Column(String(255), nullable=True)
    engineTransmission_clutch_cc_value_2 = Column(String(255), nullable=True)
    engineTransmission_clutch_cc_value_3 = Column(String(255), nullable=True)
    engineTransmission_clutch_cc_value_4 = Column(String(255), nullable=True)
    engineTransmission_clutch_cc_value_5 = Column(String(255), nullable=True)
    engineTransmission_clutch_cc_value_6 = Column(String(255), nullable=True)
    engineTransmission_gearShifting_value = Column(String(255))
    engineTransmission_gearShifting_cc_value_0 = Column(String(255), nullable=True)
    engineTransmission_gearShifting_cc_value_1 = Column(String(255), nullable=True)
    engineTransmission_gearShifting_cc_value_2 = Column(String(255), nullable=True)
    engineTransmission_comments_value_0 = Column(String(255), nullable=True)
    engineTransmission_comments_value_1 = Column(String(255), nullable=True)
    engineTransmission_comments_value_2 = Column(String(255), nullable=True)
    engineTransmission_comments_value_3 = Column(String(255), nullable=True)
    engineTransmission_comments_value_4 = Column(String(255), nullable=True)
    fuel_type = Column(String(255))
    odometer_reading = Column(Integer)
    rating_engineTransmission = Column(Float)
