CREATE DATABASE IF NOT EXISTS blueyonder;
USE blueyonder;
CREATE TABLE IF NOT EXISTS blueyonder.engine_inspection(
appointmentId VARCHAR(100),
inspectionStartTime  DATETIME NOT NULL,
year YEAR NOT NULL,
month INT(2) NOT NULL,
engineTransmission_battery_value VARCHAR(100),
engineTransmission_battery_cc_value_0 VARCHAR(100) NULL,
engineTransmission_battery_cc_value_1 VARCHAR(100) NULL,
engineTransmission_battery_cc_value_2 VARCHAR(100) NULL,
engineTransmission_battery_cc_value_3 VARCHAR(100) NULL,
engineTransmission_battery_cc_value_4 VARCHAR(100) NULL,
engineTransmission_engineoilLevelDipstick_value VARCHAR(100),
engineTransmission_engineOilLevelDipstick_cc_value_0 VARCHAR(100) NULL,
engineTransmission_engineOil VARCHAR(100) NOT NULL,
engineTransmission_engineOil_cc_value_0 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_1 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_2 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_3 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_4 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_5 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_6 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_7 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_8 VARCHAR(100) NULL,
engineTransmission_engineOil_cc_value_9 VARCHAR(100) NULL,
engineTransmission_engine_value VARCHAR(100) NOT NULL,
engineTransmission_engine_cc_value_0 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_1 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_2 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_3 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_4 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_5 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_6 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_7 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_8 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_9 VARCHAR(100) NULL,
engineTransmission_engine_cc_value_10 VARCHAR(100) NULL,
engineTransmission_coolant_value VARCHAR(100) NOT NULL,
engineTransmission_coolant_cc_value_0 VARCHAR(100)  NULL,
engineTransmission_coolant_cc_value_1 VARCHAR(100) NULL,
engineTransmission_coolant_cc_value_2 VARCHAR(100) NULL,
engineTransmission_coolant_cc_value_3 VARCHAR(100) NULL,
engineTransmission_engineMounting_value VARCHAR(100) NOT NULL,
engineTransmission_engineMounting_cc_value_0 VARCHAR(100) NULL,
engineTransmission_engineSound_value VARCHAR(100) NOT NULL,
engineTransmission_engineSound_cc_value_0 VARCHAR(100) NULL,
engineTransmission_engineSound_cc_value_1 VARCHAR(100) NULL,
engineTransmission_engineSound_cc_value_2 VARCHAR(100) NULL,
engineTransmission_engineSound_cc_value_3 VARCHAR(100) NULL,
engineTransmission_engineSound_cc_value_4 VARCHAR(100) NULL,
engineTransmission_engineSound_cc_value_5 VARCHAR(100) NULL,
engineTransmission_exhaustSmoke_value VARCHAR(100) NOT NULL,
engineTransmission_exhaustSmoke_cc_value_0 VARCHAR(100),
engineTransmission_engineBlowByBackCompression_value VARCHAR(100) NOT NULL,
engineTransmission_engineBlowByBackCompression_cc_value_0 VARCHAR(100) NULL,
engineTransmission_clutch_value VARCHAR(100) NOT NULL,
engineTransmission_clutch_cc_value_0 VARCHAR(100) NULL,
engineTransmission_clutch_cc_value_1 VARCHAR(100) NULL,
engineTransmission_clutch_cc_value_2 VARCHAR(100) NULL,
engineTransmission_clutch_cc_value_3 VARCHAR(100) NULL,
engineTransmission_clutch_cc_value_4 VARCHAR(100) NULL,
engineTransmission_clutch_cc_value_5 VARCHAR(100) NULL,
engineTransmission_clutch_cc_value_6 VARCHAR(100) NULL,
engineTransmission_gearShifting_value VARCHAR(100) NULL,
engineTransmission_gearShifting_cc_value_0 VARCHAR(100) NULL,
engineTransmission_gearShifting_cc_value_1 VARCHAR(100) NULL,
engineTransmission_gearShifting_cc_value_2 VARCHAR(100) NULL,
engineTransmission_comments_value_0 VARCHAR(100) NULL,
engineTransmission_comments_value_1 VARCHAR(100) NULL,
engineTransmission_comments_value_2 VARCHAR(100) NULL,
engineTransmission_comments_value_3 VARCHAR(100) NULL,
engineTransmission_comments_value_4 VARCHAR(100) NULL,
fuel_type ENUM("Petrol + CNG", "Diesel", "Petrol"),
odometer_reading INTEGER,
rating_engineTransmission TINYINT,
PRIMARY KEY(appointmentId),
CONSTRAINT CHECK_MONTH CHECK (month>0 AND month<13))
ENGINE=MEMORY;