name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file /home/runner/work/FastAPI_BlueYonder/FastAPI_BlueYonder/services/Dockerfile --tag api_server:$(date +%s)
